site_name: SUMMIT
theme:
  name: material
  custom_dir: overrides
  logo: assets/White 144.png
  favicon: assets/White 144.png
  features:
    - navigation.tabs

extra_css:
  - stylesheets/landing.css

nav:
  - Home: index.md
  - Building Go: building-go.md
  - Building Python: building-python.md
  - Go Analytics: 
    - Optical Character Recognition: go-analytics/optical-character-recognition.md
    - Image Classification: go-analytics/image-classification.md
    - Object Detection: go-analytics/object-detection.md
    - NSFW Detection: go-analytics/nsfw-detection.md
  - Python Analytics: 
    - Named Entity Recognition: python-analytics/named-entity-recognition.md
    - Text Classification: python-analytics/text-classification.md
    - Sentiment Analysis: python-analytics/sentiment-analysis.md
    - Topic Modeling: python-analytics/topic-modeling.md