[project]
name = "loader"
version = "0.1.0"
description = "Loader lambda"
requires-python = ">=3.12"
dependencies = [
    "data-core",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
